### ISSUE TITLE
Enhancement of Readme file

### ISSUE THREAD

**Issue by payallenka** [IgKniteDev/IgKnite#116]
### Description

I would like to contribute to your project by adding the Screenshot of the output - that is displayed when the code is run on VSCode.
I wish to participate in hacktoberfest. It will be great if you allow to add hacktoberfest this issue.

**Comment by payallenka** [comment]
thank you assigning the task to me but I think you have added the spam, invalid tag to it. Kind request to please remove those tags and add the hacktoberfest tag.

**Comment by furtidev** [comment]
> thank you assigning the task to me but I think you have added the spam, invalid tag to it. Kind request to please remove those tags and add the hacktoberfest tag.
@payallenka Hi, why do you think it's necessary? Does it serve any purpose at all? Especially when nothing special is printed to the console when the bot is run. 🤔 Anyway, these are the questions you should ask yourself before opening up an issue or a PR. I don't think this addition is needed because it makes no sense whatsoever. Sorry, and thanks for the effort. 🙏
